name: Share Your Shalom
favicon: null
layout_spectrum: 0.8769509445410222
typography_spectrum: 0.390630176756531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1351429931819439
  lightness: 0.3729700851254165
  saturation: 0.05029105884023011
  rhythmicContrast: 0.8285860540345311
purpose: []
